### ISSUE TITLE
Syntax errors cause meteor process to die

### ISSUE THREAD

**Issue by qbolec** [barbatus/typescript#21]
While it seems that type errors and other semantic errors are handled quite robutst by the `meteor` watch-and-recompile process, I have problems with syntax errors. If there is a misplaced `;` in place of `,` in an object literal for example, then the whole `meteor` procces exits unexpectedly leaving me with no clue about which file and line of my source code caused the error. I have to run `tsc --out /dev/null file.js` on the files I suspect one by one, until I find the error.
Here is an example output:
```
$ meteor
[[[[[ ~/projects/web-demo/web-app ]]]]]

=> Started proxy.
=> Started MongoDB.

/home/jlopuszanski/.meteor/packages/less/.2.6.0.1p4eefj++os+web.browser+web.cordova/plugin.compileLessBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:116
      throw error;
            ^
TypeError: Cannot set property './initialize-database.js' of undefined
    at ImportScanner._checkSourceAndTargetPaths (/tools/isobuild/import-scanner.js:256:7)
    at /tools/isobuild/import-scanner.js:159:12
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:158:11)
    at /tools/isobuild/compiler-plugin.js:834:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:805:19)
    at ServerTarget._emitResources (/tools/isobuild/bundler.js:913:8)
    at /tools/isobuild/bundler.js:684:12
    at /tools/utils/buildmessage.js:359:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:352:34
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:350:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.enterJob (/tools/utils/buildmessage.js:324:26)
    at ServerTarget.make (/tools/isobuild/bundler.js:675:18)
    at /tools/isobuild/bundler.js:2502:14
    at /tools/isobuild/bundler.js:2570:20
    at /tools/utils/buildmessage.js:271:13
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:264:29
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:262:18
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at /tools/utils/buildmessage.js:253:23
    at [object Object].withValue (/tools/utils/fiber-helpers.js:89:14)
    at Object.capture (/tools/utils/buildmessage.js:252:19)
    at Object.exports.bundle (/tools/isobuild/bundler.js:2455:31)
    at /tools/runners/run-app.js:591:36
    at Function.run (/tools/tool-env/profile.js:489:12)
    at bundleApp (/tools/runners/run-app.js:581:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:634:35)
    at AppRunner._fiber (/tools/runners/run-app.js:887:28)
    at /tools/runners/run-app.js:411:12
```
And here is a more helpful output of the `tsc`:
```
$ tsc --out /dev/null server/imports/startup/initialize-database.ts
server/imports/startup/initialize-database.ts(92,61): error TS1005: ')' expected.
server/imports/startup/initialize-database.ts(142,3): error TS1005: ',' expected.
```
The particular syntax error in 92 line is that I wrote:
```
  recordings.forEach((recordingDescription)=>{
    if(!Recordings.findOne({name:recordingDescription.name}){ //note the missing )
      Recordings.insert(recordingDescription);
    }
  });
```

Here is the list of packages I use:
```
$ meteor list
accounts-password             1.1.8* Password support for accounts
accounts-ui                   1.1.9  Simple templates to add login widgets to an app
barbatus:typescript           0.3.1* TypeScript for Meteor
dburles:collection-helpers    1.0.4  Transform your collections with helpers that you define
ecmascript                    0.4.3* Compiler plugin that supports ES2015+ in all .js files
es5-shim                      4.5.10* Shims and polyfills to improve ECMAScript 5 support
jquery                        1.11.8* Manipulate the DOM using CSS selectors
materialize:materialize       0.97.5  Materialize (official): A modern responsive front-end framework based on Material Design
meteor-base                   1.0.4  Packages that every Meteor app needs
mobile-experience             1.0.4  Packages for a great mobile user experience
mongo                         1.1.7* Adaptor for using MongoDB and Minimongo over DDP
peerlibrary:blaze-components  0.18.0  Reusable components for Blaze
peerlibrary:reactive-field    0.1.0  Reactive field for Meteor
reactive-var                  1.0.9* Reactive variable
reywood:publish-composite     1.4.2  Publish a set of related documents from multiple collections with a reactive join
standard-minifier-css         1.0.6* Standard css minifier used with Meteor apps by default.
standard-minifier-js          1.0.6* Standard javascript minifiers used with Meteor apps by default.
stylus                        2.511.5* Expressive, dynamic, robust CSS
tap:i18n                      1.8.0* A comprehensive internationalization solution for Meteor
tracker                       1.0.13* Dependency tracker to allow reactive callbacks
```

**Comment by barbatus** [comment]
what version are you using?

**Comment by qbolec** [comment]
It was (according to the `meteor list` above)  0.3.1.
After performing `meteor update` it got upgraded : 
```
barbatus:typescript           upgraded from 0.3.1 to 0.3.3
barbatus:typescript-compiler  upgraded from 0.5.10 to 0.6.1
```
and the problem with syntax errors got resolved. But now I have a much more severe problem: the application does not work at all.
I see errors like `lookup.js:189 Uncaught Error: No such template: SmartSearchPageComponent` in the browser's console.
I guess this is because the line with `SmartSearchPageComponent.register('SmartSearchPageComponent')` which is at the end of `SmartSearchPageComponent.ts` file.
Is there some "tree shaking" optimization going on which prevents side effects of imported modules from running?

**Comment by qbolec** [comment]
It turned out that there is a difference now between
`import '../SearchPageComponent/SearchPageComponent.ts';`
and
`import '../SearchPageComponent/SearchPageComponent';`

The later fails to recursively import subcomponents.

**Comment by barbatus** [comment]
This packages is responsible for TS compilation only not for component loading, which is done by Meteor itself. It's likely though that you are using components importing in a wrong way. So if you want me to take a look, I'll need a repo with the issue.
