### ISSUE TITLE
After upgrade form 0.6.3 to 0.6.5_1 compilation fails

### ISSUE THREAD

**Issue by scharf** [barbatus/typescript#46]
```
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:29142:20:
Cannot read property 'forEach' of 
at symbolsToArray
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:29142:20)
at Object.getExportsOfModuleAsArray
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/typescript/lib/typescript.js:25811:20)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:68:29
at Function._.each._.forEach
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/underscore/underscore.js:153:9)
at getDeps
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:61:7)
at Object.getDepsAndRefs
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/ts-utils.js:104:17)
at CompileService.CP.compile
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/compile-service.js:45:18)
at compile
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:156:35)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:171:16
at Cache.CCp.get
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/cache.js:167:19)
at TSBuild.emit
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/meteor-typescript/index.js:168:31)
at packages/barbatus:typescript-compiler/typescript-compiler.js:135:30
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:324:29
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:44:16
at packages/barbatus:typescript-compiler/typescript-compiler.js:142:7
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:182:20
at replenish
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:317:21)
at
/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:328:15
at Object.async.forEachLimit.async.eachLimit
(/home/rof/meteor/packages/barbatus_typescript/.0.6.5_1.1tjvrhq++os+web.browser+web.cordova/plugin.typescript.os/npm/node_modules/meteor/barbatus_typescript-compiler/node_modules/async/lib/async.js:221:35)
at TypeScriptCompiler.processFilesForTarget
(packages/barbatus:typescript-compiler/typescript-compiler.js:127:11)
```

**Comment by scharf** [comment]
I boiled it down to the following problem:


File `foo.ts` looks like this;

```typescript
export = 1; // whatever you want to export
```

File `bar.ts` looks like this:

```typescript
import foo = require("./foo");
```

Then the typescript compiler fails miserably.

Fortunately this is easy to fix and that style of export/import is not nice anyway.

**Comment by rwdietrich** [comment]
Have the same issue, but found after an update. None of my code uses require()

**Comment by scharf** [comment]
maybe it's the 

```typescript 
export = something;
```

**Comment by rwdietrich** [comment]
Took another look, and my error messages are similar but different. I'll post a different issue.

**Comment by scharf** [comment]
has been resolved
